name: Build and Release Executable

on:
  push:
    tags:
      - 'v*' # Se déclenche quand un tag comme v1.0.0, v1.2.3 est poussé

jobs:
  build:
    permissions:
      contents: write # Permet à l'action de créer une release

    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build the executable
        run: pyinstaller build.spec --noconfirm

      - name: Sign the executable
        shell: pwsh
        env:
          CERT_BASE64: ${{ secrets.SIGNING_CERT_BASE64 }}
          CERT_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        run: |
          # 1. Décoder le certificat
          $certBytes = [Convert]::FromBase64String($env:CERT_BASE64)
          [IO.File]::WriteAllBytes("cert.pfx", $certBytes)

          # 2. Trouver Signtool automatiquement (peu importe la version)
          $basePath = "C:\Program Files (x86)\Windows Kits\10\bin"
          $signtool = Get-ChildItem -Path $basePath -Recurse -Filter "signtool.exe" | Where-Object { $_.FullName -like "*x64*" } | Select-Object -First 1

          if (-not $signtool) {
              Write-Error "Signtool introuvable !"
              exit 1
          }
          Write-Host "Signtool trouvé ici : $($signtool.FullName)"

          # 3. Signer l'exécutable
          $ExePath = "dist/GestionnaireCles.exe"
          
          if (Test-Path $ExePath) {
              & $signtool.FullName sign /f cert.pfx /p $env:CERT_PASSWORD /tr http://timestamp.digicert.com /td SHA256 /fd SHA256 $ExePath
              Write-Host "Signature appliquée avec succès sur $ExePath"
          } else {
              Write-Error "Impossible de trouver $ExePath pour le signer."
              exit 1
          }

          # 4. Nettoyage
          Remove-Item "cert.pfx"

      - name: Prepare artifact name
        id: artifact_name
        shell: bash
        run: |
          # Préparer le nom et le chemin attendu pour la build Windows
          echo "NAME=GestionnaireCles-Windows.zip" >> $GITHUB_ENV
          echo "PATH_TO_ARTIFACT=dist/GestionnaireCles.exe" >> $GITHUB_ENV

      - name: Zip artifact
        uses: papeloto/action-zip@v1
        with:
          files: dist/GestionnaireCles.exe
          dest: GestionnaireCles-Windows.zip

      - name: Upload artifact to release
        uses: softprops/action-gh-release@v1
        with:
          files: GestionnaireCles-Windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}